"""delete  brand

Revision ID: 18aa1ce24164
Revises: 8bc90f816482
Create Date: 2024-10-18 17:50:02.048558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aa1ce24164'
down_revision: Union[str, None] = '8bc90f816482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_brand_id', table_name='product')
    op.drop_constraint('fk_brand_id', 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_brand_id', 'product', 'brand', ['brand_id'], ['id'])
    op.create_index('ix_product_brand_id', 'product', ['brand_id'], unique=False)
    # ### end Alembic commands ###
