"""migratios for models purchase_order

Revision ID: 18c0dbcaa7b9
Revises: bc82673887f9
Create Date: 2024-10-18 03:28:13.609578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c0dbcaa7b9'
down_revision: Union[str, None] = 'bc82673887f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('txt_address', sa.String(length=300), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'company_id', name='uq_supplier_email'),
    sa.UniqueConstraint('tax_id', 'company_id', name='uq_tax_id')
    )
    op.create_index(op.f('ix_supplier_company_id'), 'supplier', ['company_id'], unique=False)
    op.create_index(op.f('ix_supplier_email'), 'supplier', ['email'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sumpplier_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=300), nullable=False),
    sa.Column('order_description', sa.String(length=300), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_id'),
    sa.ForeignKeyConstraint(['sumpplier_id'], ['supplier.id'], name='fk_supplier_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code', 'company_id', name='uq_order_code_id')
    )
    op.create_index(op.f('ix_purchase_order_company_id'), 'purchase_order', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_sumpplier_id'), 'purchase_order', ['sumpplier_id'], unique=False)
    op.create_table('purchase_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_id'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_product_id'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['purchase_order.id'], name='fk_purchase_order_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_detail_company_id'), 'purchase_detail', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_detail_product_id'), 'purchase_detail', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_detail_sales_order_id'), 'purchase_detail', ['sales_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_detail_sales_order_id'), table_name='purchase_detail')
    op.drop_index(op.f('ix_purchase_detail_product_id'), table_name='purchase_detail')
    op.drop_index(op.f('ix_purchase_detail_company_id'), table_name='purchase_detail')
    op.drop_table('purchase_detail')
    op.drop_index(op.f('ix_purchase_order_sumpplier_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_company_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_supplier_email'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_company_id'), table_name='supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###
