"""delete rbac

Revision ID: 8a94f6dde329
Revises: 18aa1ce24164
Create Date: 2024-10-19 01:30:54.658871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a94f6dde329'
down_revision: Union[str, None] = '18aa1ce24164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tax_address', sa.String(length=300), nullable=True))
    op.add_column('supplier', sa.Column('tax_address', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('supplier', 'tax_address')
    op.drop_column('company', 'tax_address')


